config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  # root 'projects#index'

  # 首页设置为本周周报
  root 'weeklies#this_week'


  resources :projects do
    resources :workflows
    member do
      get :invite_manager
      post :manage_in
      post :refuse
    end
     
  end

  resources :my_projects

  # 我的团队
  resources :sbus


  # 管理员路由
  namespace :admin do
    resources :workflows
    resources :users do
      member do 
        post :set_admin
        post :cancel_admin
        post :set_pm
        post :cancel_pm
      end 

      resources :weeklies

    end
    resources :projects do
      member do
        post :enable_workflow
        post :disable_workflow
      end
    end
    resources :weekly_templates
    resources :sbus
    resources :units
  end



  # 普通用户
  resources :weeklies do
    collection do
      get :this_week
    end
    resources :workflows
  end
  resources :users

  # 其他页面
  resources :landingpage do
    collection do
      # 帮助
      get :faq
    end
  end



  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      get "/projects/:project_code" => "projects#normal", as: :project
      get "/users/:itcode" => "users#normal", as: :user
      # resources :trains, only: [:index, :show]
      # resources :reservations, ony:[:show, :create, :update, :destroy] 
      # 为了更明白的给api 使用者显示,所以最好手动列出来,并且将'id'换成对应的参数
      # get "/projects/:project_code" => "projects#show", as: :project
    end
  end

end

app/controllers/my_projects_controller.rb
class MyProjectsController < ApplicationController

  def index
    @projects = current_user.manage_projects
  end


  def show
    @project = Project.find(params[:id])
    @workflows = @project.workflows_group_by_project
    @workflow_user_groups = @project.workflows_group_by_user
  end

end

app/helpers/my_projects_helper.rb
module MyProjectsHelper
end

app/views/my_projects/index.html.erb
<div class="col-md-2 text-right">


    <h1>我管理的项目</h1>

  
</div>
<div class="col-md-10">



  <ol class="breadcrumb">
    <li class="active">项目</li>
  </ol>



  <table class="table table-striped">
    <thead>
      <tr>
        <td>项目名</td>
        <td>项目描述</td>

      </tr>
    </thead>
    <tbody>
      <% @projects.each do |project| %>
      <tr>
        <td><%= link_to(project.name,my_project_path(project)) %></td>
        <td><%= project.description %></td>
      </tr>
      <% end %>
    </tbody>
  </table>


</div>  

app/views/my_projects/show.html.erb
<div class="col-md-2 text-right">


    <h1>我管理的项目</h1>

  
</div>
<div class="col-md-10">





  <ol class="breadcrumb">
    <li>
      <%= link_to('项目',my_projects_path)%>
    </li>
    <li class="active"><%= @project.name %></li>
  </ol>

  <h1>
    <%= @project.code %>#<%= @project.name %>
    <% if @project.cost_already.present?  %>
      <% if @project.cost_already>@project.cost_plan  %>
        <span class="alert-danger">超支!!</span>
      <%end%>
    <% end %>
  </h1>

  <p>
    <%= @project.description %>
  </p>


  <p>销售: <%= @project.sales_name %></p>
  <p>部门: <%= @project.sbu %></p>


<p>
项目经理:
<% @project.managers.each do |manager| %>
  <code><%= manager.name %></code>
<% end %>  
</p>

<p>
  项目成员:
  <% @project.members.each do |member| %>
  <code><%= member.name %></code>
  <% end %>  
</p>



<p>
   已发生费用: <%= number_with_delimiter(@project.cost_already) %>/
   <%= number_with_delimiter(@project.cost_plan) %>
   元(预留)
</p>
<p>
   剩余成本: 
   <%  if @project.cost_already.present? %>
    <% if @project.cost_already>@project.cost_plan  %>
      <span class="alert-danger"><%=number_with_delimiter(@project.cost_plan-@project.cost_already) %></span>
      <%else%>
      <span><%=number_with_delimiter(@project.cost_plan-@project.cost_already) %></span>
      
     <%end%>
      元
  <% end %>


</p>

  <hr>
  <%#= link_to('报工',new_project_workflow_path(@project),class: "btn btn-primary")  %>


  <%= render "common/workflows_usergroup_table" %>




  </table>


</div>  