config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  # root 'projects#index'

  # 首页设置为本周周报
  root 'weeklies#this_week'


  resources :projects do
    resources :workflows
    member do
      get :invite_manager
      post :manage_in
      post :refuse
    end
     
  end

  resources :my_projects

  # 我的团队
  resources :sbus


  # 管理员路由
  namespace :admin do
    resources :workflows
    resources :users do
      member do 
        post :set_admin
        post :cancel_admin
        post :set_pm
        post :cancel_pm
      end 

      resources :weeklies

    end
    resources :projects do
      member do
        post :enable_workflow
        post :disable_workflow
      end
    end
    resources :weekly_templates
    resources :sbus
    resources :units
  end



  # 普通用户
  resources :weeklies do
    collection do
      get :this_week
    end
    resources :workflows
  end
  resources :users

  # 其他页面
  resources :landingpage do
    collection do
      # 帮助
      get :faq
    end
  end



  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      get "/projects/:project_code" => "projects#normal", as: :project
      get "/users/:itcode" => "users#normal", as: :user
      # resources :trains, only: [:index, :show]
      # resources :reservations, ony:[:show, :create, :update, :destroy] 
      # 为了更明白的给api 使用者显示,所以最好手动列出来,并且将'id'换成对应的参数
      # get "/projects/:project_code" => "projects#show", as: :project
    end
  end

end

app/models/project.rb
class Project < ApplicationRecord

  has_many :workflows

  has_many :project_relationships
  has_many :members, through: :project_relationships, source: :user


  # 管理员关系
  has_many :project_manages
  has_many :managers, through: :project_manages, source: :user


  scope :order_by_created_at, -> { order("created_at DESC") }


  # 判断是否已经在项目组中
  def is_members?(user)
    members.include?(user)
  end



  # 成员加入项目
  def join!(user)
    members << user
  end



  # 判断是否已经在项目组中
  def is_managers?(user)
    managers.include?(user)
  end



  # 成员加入项目
  def join_manager!(user)
    managers << user
  end




  # 是否禁止报工
  def workflow_disabled?
    self.disable_workflow
  end


  # 禁止报工
  def workflow_disabled!
    self.disable_workflow = true
    self.save
  end

  # 开启报工
  def workflow_enabled!
    self.disable_workflow = false
    self.save
  end



  # 成员退出项目
  def exit!(user)
    members.delete(user)
    if is_managers?(user)
      managers.delete(user)  
    end
  end  


  def hours_sum
    sum = 0
    self.workflows.pluck(:hours).each do |h|
      sum = sum + h
    end
    sum
  end


  def workhours(user_id)
    user_workflows = self.workflows.where(user_id: user_id)
    sum = 0
    user_workflows.each do |w|
      sum = sum + w.hours
    end
    sum
  end


  def workflows_group_by_project
    self.workflows.group_by{|w| w.project}
  end


  def workflows_group_by_user
    self.workflows.group_by{|w| w.user}
  end


  # 一个项目都用到了哪些产品
  def used_companies
    company_list = []
    self.workflows.each do |w|
      company_list << w.companies
    end
    company_list = company_list.flatten.uniq
  end


  # 涉及的产品及工作量
  def used_companies_hours
    companies_hour_obj = {}
    self.used_companies.each do |c|
      companies_hour_obj[c.name] = 0
    end
    # 循环每个工作流
    self.workflows.each do |w|
      # 涉及的产品公司
      self.used_companies.each do |c|
        if w.companies.include?(c)
          companies_hour_obj[c.name] = companies_hour_obj[c.name]+w.hours
        end
      end
    end
    companies_hour_obj
  end


  # 搜索常规项目
  def self.search_normal(search)
    if search
      where('name LIKE ? or code LIKE ? or sales_name like ?',"%#{search}%","%#{search}%","%#{search}%")
    else
      scoped
    end
  end

  # 搜索常规项目
  def self.search_temp(search)
    if search
      where('name LIKE ? and is_temp = ?', "%#{search}%",true)
    else
      scoped
    end
  end




  def addCost!(cost)
    self.cost_already.present? ? self.cost_already=self.cost_already+cost : self.cost_already=cost 
    self.save
  end



  # def self.to_csv(options = {})
  #   CSV.generate(options) do |csv|
  #     csv << column_names
  #     all.each do |project|
  #       csv << project.attributes.values_at(*column_names)
  #     end
  #   end.encode('gb2312', :invalid => :replace, :undef => :replace, :replace => "?") 
  # end

end

# == Schema Information
#
# Table name: projects
#
#  id                 :integer          not null, primary key
#  name               :string
#  description        :string
#  project_type       :string
#  start_time         :datetime
#  end_time           :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  code               :string
#  sales_name         :string
#  sbu                :string
#  disable_workflow   :boolean          default(FALSE)
#  cost_plan          :integer
#  cost_already       :integer
#  project_class      :string
#  customer_company   :string
#  customer_name      :string
#  customer_phone     :string
#  pm_name            :string
#  area               :string
#  project_start_time :string
#  project_end_time   :string
#  submit_plan        :string
#  other              :string
#  is_temp            :boolean          default(FALSE)
#  following_sbu      :string
#

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  layout "admin"
  def index

    @q = Project.ransack(params[:q])
    @projects = @q.result(distinct: true).order_by_created_at.paginate(:page => params[:page], :per_page => 10)

    # @projects = Project.all.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html
      format.csv { send_data @projects.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
    
  end

  def new
     @project = Project.new
     @units = Unit.pluck(:name)
     @following_sbus = Sbu.pluck(:name)
  end

  def create
    @project = Project.new(project_params)
    if (Project.find_by_name(@project.name)).present?
      flash[:alert] = '项目名已存在'
      render :new
    else
      if @project.save
        flash[:notice] = '项目新建成功!'
        redirect_to admin_project_path(@project)
      else
        flash[:alert] = '项目新建失败'
        render :new    
      end  
    end
  
  end




  def show
    @project = Project.find(params[:id])
    @project_sum_hours = @project.hours_sum
    @workflow_user_groups = @project.workflows_group_by_user
  end

  def edit
    @project = Project.find(params[:id])
    @units = Unit.pluck(:name)
    @following_sbus = Sbu.pluck(:name)
  end


  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    if @project.save
      flash[:notice] = '项目更新成功!'
      redirect_to admin_project_path(@project)
    else
      flash[:alert] = '项目更新失败'
      render admin_project_path(@project)    
    end      
  end


  def destroy
    @project = Project.find(params[:id])
    if @project.delete
      flash[:notice] = '项目删除成功!'
      redirect_to admin_projects_path
    else
      flash[:alert] = '项目删除失败'
      render admin_projects_path    
    end        
  end



  # 禁止报工
  def disable_workflow
    @project = Project.find(params[:id])
    @project.workflow_disabled!
    redirect_to admin_project_path(@project)
  end

  # 重新开启报工
  def enable_workflow
    @project = Project.find(params[:id])
    @project.workflow_enabled!
    redirect_to admin_project_path(@project)
  end


  
  private

  def project_params
    params.require(:project).permit(:code,:name,:description,:sales_name,:cost_plan,:sbu,:following_sbu,:project_type,:start_time,:end_time,:project_class,:customer_company,:customer_name,:customer_phone,:pm_name,:area,:submit_plan,:other)
  end



end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < ApiController

  # 检索正式项目
  def normal
    @projects = Project.search_normal(params[:project_code])

    if @projects.present?
      render json: {
          stat: 1,
          data: @projects.map{ |project|

            {
              id: project.id,
              code: project.code,
              name: project.name,
              project_type: project.project_type,
              sbu: project.sbu,
              sales_name: project.sales_name
            }
          }
        }  
    else
      render json: {
        stat: 0,
        data: []
      }  
    end  

  end

  # 临时项目
  def temp
    @projects = Project.search_temp(params[:project_code])

    if @projects.present?
      render json: {
          stat: 1,
          data: @projects.map{ |project|

            {
              id: project.id,
              code: project.code,
              name: project.name,
              project_type: project.project_type,
              sbu: project.sbu,
              sales_name: project.sales_name
            }
          }
        }  
    else
      render json: {
        stat: 0,
        data: []
      }  
    end  
    
  end


  # def show
  #   @project = Project.find_by_code(params[:project_code])

  #   if @project.present?
  #     # 如果该项目已经停止报工提示下
  #     if @project.workflow_disabled?
  #       render json: {
  #         stat: 2,
  #         data:{
  #           id: @project.id,
  #           code: @project.code,
  #           name: @project.name,
  #           project_type: @project.project_type,
  #           sbu: @project.sbu,
  #           sales_name: @project.sales_name
  #         }
  #       }   
  #     else
  #       render json: {
  #         stat: 1,
  #         data:{
  #           id: @project.id,
  #           code: @project.code,
  #           name: @project.name,
  #           project_type: @project.project_type,
  #           sbu: @project.sbu,
  #           sales_name: @project.sales_name
  #         }
  #       }        
  #     end
  #   else
  #     render json: {
  #       stat: 0
  #     }  
  #   end
  # end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout "user"

  before_action :current_week

  def index
    @projects = current_user.projects
  end

  def show
    @project = Project.find(params[:id])
    @workflows = @project.workflows_group_by_project
    @workflow_user_groups = @project.workflows_group_by_user
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    @project.members << current_user
    @project.managers << current_user
    if @project.save
      flash[:notice] = '项目新建成功!'
      redirect_to admin_projects_path
    else
      flash[:alert] = '项目新建失败'
      render :new    
    end    
  end


  # 邀请加入
  def invite
    @project = Project.find(params[:id])
  end

  # 加入项目
  def join_in
    @project = Project.find(params[:id])
    if @project.is_members?(current_user)
      flash[:warning] = '你已经在该项目中!'
    else
      @project.join!(current_user)
      flash[:success] = '成功加入该项目!'
    end
    redirect_to project_path(@project)
  end


  # 邀请管理
  def invite_manager
    @project = Project.find(params[:id])
  end

  # 加入项目管理
  def manage_in
    @project = Project.find(params[:id])
    if @project.is_managers?(current_user)
      flash[:warning] = '你已经在该项目中!'
    else
      if !@project.is_members?(current_user)
        @project.join!(current_user)
      end
      @project.join_manager!(current_user)
      flash[:success] = '成功加入该项目!'
    end
    redirect_to my_project_path(@project)
  end



  # 拒绝加入项目
  def refuse
    @project = Project.find(params[:id])
    flash[:success] = '您拒绝了加入'+@project.name+'项目的邀请!'
    redirect_to :root
  end





  private

  def project_params
    params.require(:project).permit(:code,:name,:description,:sales_name,:sbu,:project_type,:start_time,:end_time)
  end

  def current_week
    @current_weekly = current_user.weeklies.last
    @start_time =@current_weekly.start_time.strftime("%Y-%m-%d")
    @end_time =@current_weekly.end_time.strftime("%Y-%m-%d")
  end

end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/api/v1/projects_helper.rb
module Api::V1::ProjectsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/projects/_form.html.erb
<%= simple_form_for(['admin',@project]) do |f| %>
  <div class="form-group">
    <%= f.input :code,label: '项目号',placeholder: "如果没有项目号,则写'临时'", input_html: { class: "form-control"} %>
    <%= f.input :name,label: '项目名', input_html: { class: "form-control"} %>
    <%= f.input :project_type,label: '项目类型',collection: ['集成','供货','集成售前','解决方案售前','单次服务','服务','临时','厂商交流','技术提升','部门工作','认证考试','休假'], input_html: { class: "form-control"} %>
    <%= f.input :project_class,label: '项目级别',collection: ['A','B','C','D','W'], input_html: { class: "form-control"} %>
    <%= f.input :sales_name,label: '销售', input_html: { class: "form-control"} %>
    <%= f.input :sbu,placeholder: "对应项目结算的最终部门",label: '结算部门', input_html: { class: "form-control"},collection: @units %>
    <%= f.input :following_sbu,label: '绑定BU(如果是"部门工作","技术提升"或"厂商交流"")', input_html: { class: "form-control"},collection: @following_sbus %>
    <%= f.input :customer_company,label: '客户公司名', input_html: { class: "form-control"} %>
    <%= f.input :customer_name,label: '客户联系人', input_html: { class: "form-control"} %>
    <%= f.input :customer_phone,label: '客户联系方式', input_html: { class: "form-control"} %>
    <%= f.input :area,label: '地区', input_html: { class: "form-control"} %>
    <%= f.input :pm_name,label: 'PM姓名', input_html: { class: "form-control"} %>

    <%= f.input :cost_plan,label: '预留费用(元)', input_html: { class: "form-control"} %>

    <%= f.input :submit_plan,label: '是否提交项目计划',collection: ['N','Y'], input_html: { class: "form-control"} %>

    <%= f.input :description,label: '项目描述',as: :text, input_html: { class: "form-control"} %>

    
    <%= f.input :other,label: '其他',as: :text, input_html: { class: "form-control"} %>

    <label for="">开始日期</label>

    <%= f.datetime_select :start_time,:discard_hour => true %>
    <br> 

    <label for="">结束日期</label>

    <%= f.datetime_select :end_time,:discard_hour => true %>



  </div>
  <%= f.submit "提交", class: "btn btn-primary", data: { disable_with: "提交中..." } %>
<% end %>

app/views/admin/projects/edit.html.erb
<ol class="breadcrumb">
  <li>
    <%= link_to('项目',admin_projects_path)%>
  </li>
  <li class="active">编辑项目</li>
</ol>



<%= render 'form' %>

app/views/admin/projects/index.html.erb
<%= search_form_for ['admin',@q], html: {class: "navbar-form navbar-left"} do |f|  %>
  <div class="form-group">
    <%= f.search_field :code_or_name_cont, class: "form-control", placeholder: "输入项目名或项目号"  %>
    <%= f.submit "搜索", class: "btn btn-warning"  %>
    <%#=sort_link(@q, :name)  %>
  </div>
<% end %>

<div class="row"></div>

<%= link_to('新建项目',new_admin_project_path,class: 'btn btn-primary') %>


<table class="table">
  <thead>
    <tr>
      <td>项目号</td>
      <td>项目名</td>
      <td>项目经理</td>
      <td>状态</td>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <% if project.workflow_disabled?  %>
        <tr class="alert alert-danger">
      <% else %>
        <tr class="alert alert-success">
      <% end %>
        <td><%= link_to(project.code,admin_project_path(project)) %></td>
        <td><%= link_to(project.name,admin_project_path(project)) %></td>
        <td>
          <% project.managers.each do |manager| %>
            <code><%= manager.itcode %></code>
          <% end %>  
        </td>
        <td>
          <% if project.workflow_disabled?  %>
            已停止报工
          <% else %>
            进行中..
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= will_paginate @projects %>
</div>

app/views/admin/projects/new.html.erb
<ol class="breadcrumb">
  <li>
    <%= link_to('项目',admin_projects_path)%>
  </li>
  <li class="active">新建项目</li>
</ol>



<%= render 'form' %>

app/views/admin/projects/show.html.erb
<ol class="breadcrumb">
  <li>
    <%= link_to('项目',admin_projects_path)%>
  </li>
  <li class="active"><%= @project.name %></li>
</ol>

<h1>
  <%= @project.code %>#<%= @project.name %>
</h1>

<p>
  <%= @project.description %>
</p>


<p>
  <%= @project.project_type %>
</p>

<p>销售: <%= @project.sales_name %></p>
<p>部门: <%= @project.sbu %></p>



<p>
  报工状态:
  <% if @project.workflow_disabled?  %>
    已停止报工
  <% else %>
    进行中..
  <% end %>
</p>



<p>
涉及产品:
<% if @project.used_companies_hours.present? %>
  <% @project.used_companies_hours.each do |key,value|  %>
    <code><%= key %>#<%= value %>h</code>
  <% end %>
<% end %>
</p>

<p>
项目参与人数:
<%= @workflow_user_groups.count %>人  
</p>


<p>
项目经理:
<% @project.managers.each do |manager| %>
  <code><%= manager.itcode %></code>
<% end %>  
</p>


<p>
项目参与者:
<% @project.members.each do |member| %>
  <code><%= member.itcode %>#<%= @project.workhours(member) %>h</code>
<% end %>  
</p>

<p>当前工作量合计:
<%= @project.hours_sum %>小时
</p>

<p>项目经理邀请链接: <%= link_to(  'http://daily.dcits.com'+invite_manager_project_path,invite_manager_project_path) %>
  </p>


<hr>
<%= link_to('编辑',edit_admin_project_path(@project),class: "btn btn-primary")  %>

<%= link_to('删除',admin_project_path(@project),method: 'DELETE',class: "btn btn-danger")  %>

  <% if @project.workflow_disabled?  %>
    <%= link_to('开启继续报工',enable_workflow_admin_project_path(@project),method: 'post',class: "btn btn-warning") %></td>
  <% else %>
    <%= link_to('禁止继续报工',disable_workflow_admin_project_path(@project),method: 'post',class: "btn btn-danger") %></td>
  <% end %>





  <% if @project.workflow_disabled?  %>
    <div class="alert alert-danger">
      已停止报工
    </div>
  <% else %>
    <div class="alert alert-success">
      进行中..
    </div>
  <% end %>

<%= render "common/workflows_usergroup_table" %>