config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  # root 'projects#index'

  # 首页设置为本周周报
  root 'weeklies#this_week'


  resources :projects do
    resources :workflows
    member do
      get :invite_manager
      post :manage_in
      post :refuse
    end
     
  end

  resources :my_projects

  # 我的团队
  resources :sbus


  # 管理员路由
  namespace :admin do
    resources :workflows
    resources :users do
      member do 
        post :set_admin
        post :cancel_admin
        post :set_pm
        post :cancel_pm
      end 

      resources :weeklies

    end
    resources :projects do
      member do
        post :enable_workflow
        post :disable_workflow
      end
    end
    resources :weekly_templates
    resources :sbus
    resources :units
  end



  # 普通用户
  resources :weeklies do
    collection do
      get :this_week
    end
    resources :workflows
  end
  resources :users

  # 其他页面
  resources :landingpage do
    collection do
      # 帮助
      get :faq
    end
  end



  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      get "/projects/:project_code" => "projects#normal", as: :project
      get "/users/:itcode" => "users#normal", as: :user
      # resources :trains, only: [:index, :show]
      # resources :reservations, ony:[:show, :create, :update, :destroy] 
      # 为了更明白的给api 使用者显示,所以最好手动列出来,并且将'id'换成对应的参数
      # get "/projects/:project_code" => "projects#show", as: :project
    end
  end

end

app/models/sbu.rb
class Sbu < ApplicationRecord

  has_many :sbu_leaders
  has_many :sbu_managers, through: :sbu_leaders,source: :user


  def add_manager!(user)
    self.sbu_managers << user
    self.save
  end

end

# == Schema Information
#
# Table name: sbus
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_sbus_on_name  (name) UNIQUE
#

app/controllers/admin/sbus_controller.rb
class Admin::SbusController < ApplicationController
  layout "admin"

  def index
    @sbus = Sbu.all
  end




  def show
    @sbu = Sbu.find(params[:id])
    @users = User.where(sbu_name: @sbu.name)

    respond_to do |format|
      format.html
      # format.csv { send_data @workflows.to_csv }
      format.xls{ 
        # 设置文件名
        headers["Content-Disposition"]="attachment; filename=\"" + @sbu.name + "\""
      }  
       # { send_data @products.to_csv(col_sep: "\t") }
    end

  end



  def update
    @sbu = Sbu.find(params[:id])
    user = User.find(sbu_params[:sbu_managers])
    @sbu.add_manager!(user)
    redirect_to admin_sbus_path(@sbu)
  end

  private

  def sbu_params
    params.require(:sbu).permit(:id,:sbu_managers)
  end


end

app/controllers/sbus_controller.rb
class SbusController < ApplicationController

  def index
    @sbus = current_user.manager_sbus
  end

  def show
    @sbu = Sbu.find(params[:id])
    @users = User.where(sbu_name: @sbu.name)
    @workflows_xls = Workflow.includes(:weekly).includes(:user).where(users: {sbu_name: @sbu.name}).order("workflows.created_at DESC")
    @workflows = @workflows_xls.paginate(:page => params[:page], :per_page => 30)

    
    respond_to do |format|
      format.html
      # format.csv { send_data @workflows.to_csv }
      format.xls{ 
        # 设置文件名
        headers["Content-Disposition"]="attachment; filename=\"" + @sbu.name + ".xls\""
      }  
       # { send_data @products.to_csv(col_sep: "\t") }
    end

  end

end

app/helpers/admin/sbus_helper.rb
module Admin::SbusHelper
end

app/helpers/sbus_helper.rb
module SbusHelper
end

app/views/sbus/index.html.erb
<div class="col-md-2 text-right">

    <h1>我的团队</h1>

  
</div>
<div class="col-md-10">



  <ol class="breadcrumb">
    <li class="active">团队</li>
  </ol>



  <table class="table table-striped">
    <thead>
      <tr>
        <td>团队名</td>
      </tr>
    </thead>
    <tbody>
      <% @sbus.each do |sbu| %>
      <tr>
        <td><%= link_to(sbu.name,sbus_path(sbu)) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>


</div>  

app/views/sbus/show.html.erb
<div class="col-md-2 text-right">

    <h1>我的团队</h1>

  
</div>
<div class="col-md-10">



  <ol class="breadcrumb">
    <li class="active"><%= link_to("团队",sbus_index_path) %></li>
    <li class="active"><%= @sbu.name %></li>
  </ol>



  <div>

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#workflow" aria-controls="workflow" role="tab" data-toggle="tab">工作 <kbd><%= @workflows.count %></kbd> </a></li>
      <li role="presentation"><a href="#member" aria-controls="member" role="tab" data-toggle="tab">成员  <kbd><%= @users.count %></kbd>  </a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="workflow">


          <table class="table">
            <thead>
              <tr>
                <td>用户名</td>
                <td>项目号</td>
                <td>项目名</td>
                <td>事业部</td>
                <td>销售</td>
                <td>工作内容描述</td>
                <td>工作类型</td>
                <td>涉及厂商</td>
                <td>技术方向</td>
                <td>工作量(小时)</td>
                <td>费用(元)</td>
                <td>开始时间</td>
                <td>结束时间</td>
              </tr>
            </thead>
            <tbody>
              <% @workflows.each do |workflow| %>

                  <% companies = workflow.companies.map {|s| s.name} %>
                  <% skills = workflow.skills.map {|s| s.name} %>
                  <!-- 把其他情况加进去 -->
                  <% if workflow.other_company.present?
                    companies.push(workflow.other_company)
                  end %>

                  <% if workflow.other_skill.present?
                    skills.push(workflow.other_skill)
                  end %>
              <tr>
                <td><%= workflow.user.name %></td>
                <td><%= workflow.project.code %></td>
                <td><%= workflow.project.name %></td>
                <td><%= workflow.project.sbu %></td>
                <td><%= workflow.project_sales %></td>
                <td><%= workflow.description %></td>
                <td><%= workflow.workflow_type.name %></td>
                <td><%= companies.join(',') %></td>
                <td><%= skills.join(',') %></td>
                <td><%= workflow.hours %></td>
                <td><%= workflow.cost %></td>
                <td><%= workflow.start_time.strftime("%Y-%m-%d") %></td>
                <td><%= workflow.end_time.strftime("%Y-%m-%d") %></td>
              </tr>
              <% end %>
            </tbody>
          </table>

          <div class="text-center">
            <%= will_paginate @workflows %>
          </div>
      
      <%= link_to "导出", sbus_path(@sbu,format: "xls"),class: 'btn btn-primary btn-xs' %>

      </div>
      <div role="tabpanel" class="tab-pane" id="member">

        <table class="table">
          <thead>
            <tr>
              <td>用户名</td>
              <td>itcode</td>
              <td>职位</td>
              
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= link_to(user.name,user_path(user))%></td>
                <td><%= user.itcode %></td>
                <td><%= user.title %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        
      </div>
    </div>

  </div>













</div>  

app/views/sbus/show.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="明细">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">用户名</Data></Cell>
        <Cell><Data ss:Type="String">项目号</Data></Cell>
        <Cell><Data ss:Type="String">项目名</Data></Cell>
        <Cell><Data ss:Type="String">事业部</Data></Cell>
        <Cell><Data ss:Type="String">销售</Data></Cell>
        <Cell><Data ss:Type="String">工作内容描述</Data></Cell>
        <Cell><Data ss:Type="String">工作类型</Data></Cell>
        <Cell><Data ss:Type="String">涉及厂商</Data></Cell>
        <Cell><Data ss:Type="String">技术方向</Data></Cell>
        <Cell><Data ss:Type="String">工作量</Data></Cell>
        <Cell><Data ss:Type="String">费用</Data></Cell>
        <Cell><Data ss:Type="String">开始时间</Data></Cell>
        <Cell><Data ss:Type="String">结束时间</Data></Cell>
      </Row>
    <% @workflows_xls.each do |workflow| %>

        <% companies = workflow.companies.map {|s| s.name} %>
        <% skills = workflow.skills.map {|s| s.name} %>
        <!-- 把其他情况加进去 -->
        <% if workflow.other_company.present?
          companies.push(workflow.other_company)
        end %>

        <% if workflow.other_skill.present?
          skills.push(workflow.other_skill)
        end %>
      <Row>
        <Cell><Data ss:Type="String"><%= workflow.user.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workflow.project.code %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workflow.project.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workflow.project.sbu %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workflow.project_sales %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workflow.description %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workflow.workflow_type.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= companies.join(',') %></Data></Cell>
        <Cell><Data ss:Type="String"><%= skills.join(',') %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= workflow.hours %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= workflow.cost %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workflow.start_time.strftime("%Y-%m-%d") %></Data></Cell>
        <Cell><Data ss:Type="String"><%= workflow.end_time.strftime("%Y-%m-%d") %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>