config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  # root 'projects#index'

  # 首页设置为本周周报
  root 'weeklies#this_week'


  resources :projects do
    resources :workflows
    member do
      get :invite_manager
      post :manage_in
      post :refuse
    end
     
  end

  resources :my_projects

  # 我的团队
  resources :sbus


  # 管理员路由
  namespace :admin do
    resources :workflows
    resources :users do
      member do 
        post :set_admin
        post :cancel_admin
        post :set_pm
        post :cancel_pm
      end 

      resources :weeklies

    end
    resources :projects do
      member do
        post :enable_workflow
        post :disable_workflow
      end
    end
    resources :weekly_templates
    resources :sbus
    resources :units
  end



  # 普通用户
  resources :weeklies do
    collection do
      get :this_week
    end
    resources :workflows
  end
  resources :users

  # 其他页面
  resources :landingpage do
    collection do
      # 帮助
      get :faq
    end
  end



  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      get "/projects/:project_code" => "projects#normal", as: :project
      get "/users/:itcode" => "users#normal", as: :user
      # resources :trains, only: [:index, :show]
      # resources :reservations, ony:[:show, :create, :update, :destroy] 
      # 为了更明白的给api 使用者显示,所以最好手动列出来,并且将'id'换成对应的参数
      # get "/projects/:project_code" => "projects#show", as: :project
    end
  end

end

app/views/common/_admin_sidebar.html.erb
<ul class="nav nav-pills nav-stacked">
  <li role="presentation">
    <%= link_to admin_workflows_path do %>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> 工作流
    <% end %>
  </li>



  <li role="presentation">
    <%= link_to admin_projects_path do %>
      <span class="glyphicon glyphicon-flag" aria-hidden="true"></span> 项目管理
    <% end %>
  </li>

  <li role="presentation">
    <%= link_to admin_users_path do %>
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span> 用户管理
    <% end %>
  </li>

  <li role="presentation">
    <%= link_to admin_weekly_templates_path do %>
      <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> 周报管理
    <% end %>
  </li>

  <li role="presentation">
    <%= link_to admin_sbus_index_path do %>
      <span class="glyphicon glyphicon-equalizer" aria-hidden="true"></span> 部门管理
    <% end %>
  </li>




</ul>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>


      <div class="alert alert-dismissable alert-<%= flash_class(key) %> col-md-12 col-sm-12 col-xs-12">
        <button class="close" data-dismiss="alert">×</button>
        <%= value %>
      </div>


  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 ©DCITS</p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="<%= root_path %>">
                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                <!-- <img src="https://i.loli.net/2017/12/16/5a3523bb28d35.jpg" alt="背景图像_sm.jpg" title="背景图像_sm.jpg" width="25px" height="25px" /> -->
                Daily
            </a>
        </div>

        
        <% if current_user.present? %>


        

        <p class="navbar-text"><%= current_user.name %> <span class="glyphicon glyphicon-user" aria-hidden="true"></span><%= current_user.title %>(<%=  current_user.level==''  ?  '--' : current_user.level %>)   <span class="glyphicon glyphicon-yen" aria-hidden="true"></span><%= current_user.cost || '--' %>(元/天)</p>

        <p class="navbar-text"><%=current_user.itcode%>#<%= current_user.code%>
         
          部门:<%=current_user.sbu_name%>  
          成本中心:<%=current_user.costcenter%>  
        <% end %>

        
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <!-- 用户登录系统 -->
                <% if !current_user %>
                    <!-- <li><%#= link_to("注册", new_user_registration_path) %> </li> -->
                    <li><%= link_to("登入", new_user_session_path) %></li>
                <% else %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Hi!, <%= current_user.email %>
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">

                            <% if current_user.is_admin? %>
                                <li><%= link_to("管理中心",admin_workflows_path)  %></li>
                            <% end %>


                              <li>
                                <%= link_to root_path do %>
                                    本周周报
                                <% end %>    
                              </li>

                              <li >
                                <%= link_to weeklies_path do %>
                                  历史周报
                                <% end %>
                              </li>
                              <li>
                                <%= link_to projects_path do %>
                                  参与过的项目
                                <% end %>
                              </li>
                              <li>
                                <%= link_to('我管理的项目',my_projects_path) %>
                              </li> 
                              
                              <% if current_user.manager_sbus.present? %>
                              <li>
                                <%= link_to sbus_index_path do %>
                                  我的团队
                                <% end %>
                              </li>
                              <% end %>

                        </ul>
                    </li>
                    <li> <%= link_to("帮助", faq_landingpage_index_path) %> </li>
                    <li> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                <% end %>
                <!--  -->

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/common/_user_sidebar.html.erb
<ul class="nav nav-pills nav-stacked">
  <li role="presentation">
    <%= link_to root_path do %>
      <h1>本周周报</h1>
      <p><strong>W<%= @current_weekly.week %></strong> <small>(<%= @start_time %> ~ <%= @end_time %>)</small></p>
    <% end %>
  </li>


</ul>

app/views/common/_workflows_table.html.erb
<hr>

  <% @workflows.each do |workflow| %>


  <div class="panel panel-default" style="font-size: 0.5em">
    <div class="panel-heading">
      <kbd><%= workflow[0].code %></kbd> # <kbd><%= workflow[0].sbu %></kbd> # <kbd><%= workflow[0].sales_name %></kbd>
      <h4><%= workflow[0].name %></h4>
      
    </div>
    <div class="panel-body">
      
     <table class="table table-condensed table-hover">


    <% workflow[1].each do |w| %>

    <tr>
      <td>
        
        <% companies = w.companies.map {|s| s.name} %>
        <% skills = w.skills.map {|s| s.name} %>
        <!-- 把其他情况加进去 -->
        <% if w.other_company.present?
          companies.push(w.other_company)
        end %>

        <% if w.other_skill.present?
          skills.push(w.other_skill)
        end %>






      <div class="row">
        <div class="col-md-2 col-sm-2 col-xs-2">
          <h3 class="text-center"><%= w.hours %>h</h3>
        </div>
        <div class="col-md-10 col-sm-10 col-xs-10">
          <p><em> <small><%= w.start_time.strftime("%Y-%m-%d") %> ~ <%= w.end_time.strftime("%Y-%m-%d") %></small></em> </p>
          <blockquote>

          <p style="font-size: 0.5em"><span class="glyphicon glyphicon-bookmark" aria-hidden="true"> </span>  <kbd><%= w.workflow_type.name %></kbd> </p>
            
            <% if w.description.present? %>
              
              <p><%= w.description %></p>
            <% else  %>
              <p>--</p>
            <% end %>
          


          <p style="font-size: 0.5em">
            <span class="glyphicon glyphicon-tags" aria-hidden="true"> </span> 
            <% if companies.present? %>
              <% companies.each do |c|%>
                <code><%= c %></code>
              <% end %>
            <% else %>
             -
            <% end %>

            <% if skills.present? %>
              <% skills.each do |s|%>
                <code><%= s %></code>
              <% end %>
            <% else %>
             -
            <% end %>

          </p>

          

           </blockquote>

          
          
        </div>
   

        
      </div>



      </td>
    </tr>



      



    <% end %>




       
     </table>   
      




    </div>
  </div>

<% end %>


<% if @workflows.blank? %>
  <div class="alert alert-warning" role="alert">该周没有提交周报!</div>
<% end %>

app/views/common/_workflows_usergroup_table.html.erb
<table class="table">
  <thead>
    <tr>
      <td>用户名</td>
      <td>工作量合计</td>
      
      <td>工作内容</td>
      <td>工作类型</td>
      <td>涉及厂商</td>
      <td>技术方向</td>
      <td>工作量(小时)</td>
      <td>时间</td>
    </tr>    
  </thead>
  <tbody>

    <% @workflow_user_groups.each do |workflow| %>
      <tr>
        <td rowspan="<%= workflow[1].count+1 %>"><%= workflow[0].name %></td>
        <td rowspan="<%= workflow[1].count+1 %>"><%= @project.workhours(workflow[0]) %>h</td>
      </tr>
      <% workflow[1].each do |w| %>

        <% companies = w.companies.map {|s| s.name} %>
        <% skills = w.skills.map {|s| s.name} %>
        <!-- 把其他情况加进去 -->
        <% if w.other_company.present?
          companies.push(w.other_company)
        end %>

        <% if w.other_skill.present?
          skills.push(w.other_skill)
        end %>

        <tr>
          <td><%= w.description %></td>
          <td><%= w.workflow_type.name %></td>
          <td><%= companies %></td>
          <td><%= skills %></td>
          <td><%= w.hours %>h</td>
          <td><%= w.start_time.strftime("%Y-%m-%d") %> ~ <%= w.end_time.strftime("%Y-%m-%d") %></td>        
        </tr>
      <% end %>
    <% end %>

  </tbody>



</table>